config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'home/index'
  root "home#index"
  get "citas", to: "citas#index", as: :citas
  get "peluqueria", to: "peluqueria#index", as: :peluqueria

  get 'salon/list'
  get 'salon/new'
  post 'salon/create'
  patch 'salon/update'
  get 'salon/list'
  get 'salon/show'
  get 'salon/edit'
  get 'salon/delete'
  get 'salon/update'

  get 'appointment/list'
  get 'appointment/new'
  post 'appointment/create'
  patch 'appointment/update'
  get 'appointment/list'
  get 'appointment/show'
  get 'appointment/edit'
  get 'appointment/delete'
  get 'appointment/update'

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :salon
      resources :appointment
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to  :salon
end

app/models/salon.rb
class Salon < ApplicationRecord
  def to_s
    "#{nombre}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/appointment_controller.rb
class AppointmentController < ApplicationController
  def list
    @appointments = Appointment.all
    @appointments = @appointments.sort_by{|e| e[:fecha]}
  end

  def show
    @appointment = Appointment.find(params[:id])
  end

  def new
    @appointment = Appointment.new
    @salons = Salon.all
  end

  def create
    @appointment = Appointment.create(appointment_params)

    if @appointment.save
      redirect_to :action => 'list'
    else
      @salons = Salon.all
      render :action => 'new'
    end
  end

  def edit
    @appointment = Appointment.find(params[:id])
    @salons = Salon.all
  end

  def update
    @appointment = Appointment.find(params[:id])

    if @appointment.update(appointment_param)
      redirect_to :action => 'show', :id => @appointment
    else
      @salons = Salon.all
      render :action => 'edit'
    end
  end

  def delete
    Appointment.find(params[:id]).destroy
    redirect_to :action => 'list'
  end

  private
  def appointment_params
    params.require(:appointments).permit(:persona, :fecha, :hora, :telefono, :salon_id)
  end

  def appointment_param
    params.require(:appointment).permit(:persona, :fecha, :hora, :telefono, :salon_id)
  end

  def current_appointment
    @appointment = Appointment.find(params[:id])
  end
end

app/controllers/citas_controller.rb
class CitasController < ApplicationController
  def index
  end
end

app/controllers/developers_controller.rb
class DevelopersController < ApplicationController
  before_action :set_developer, only: %i[ show edit update destroy ]

  # GET /developers or /developers.json
  def index
    @developers = Developer.all
  end

  # GET /developers/1 or /developers/1.json
  def show
  end

  # GET /developers/new
  def new
    @developer = Developer.new
  end

  # GET /developers/1/edit
  def edit
  end

  # POST /developers or /developers.json
  def create
    @developer = Developer.new(developer_params)

    respond_to do |format|
      if @developer.save
        format.html { redirect_to @developer, notice: "Developer was successfully created." }
        format.json { render :show, status: :created, location: @developer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @developer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /developers/1 or /developers/1.json
  def update
    respond_to do |format|
      if @developer.update(developer_params)
        format.html { redirect_to @developer, notice: "Developer was successfully updated." }
        format.json { render :show, status: :ok, location: @developer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @developer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /developers/1 or /developers/1.json
  def destroy
    @developer.destroy
    respond_to do |format|
      format.html { redirect_to developers_url, notice: "Developer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_developer
      @developer = Developer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def developer_params
      params.require(:developer).permit(:name, :surname, :project_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/peluqueria_controller.rb
class PeluqueriaController < ApplicationController
  def index
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name, :team, :info)
    end
end

app/controllers/salon_controller.rb
class SalonController < ApplicationController
  def list
    @salons = Salon.all
  end

  def index
    render json: Salon.all, status: :ok
  end

  def show
    @salon = Salon.find(params[:id])
  end

  def new
    @salon = Salon.new
  end

  def salon_params
    params.require(:salons).permit(:nombre, :horario, :localizacion)
  end

  def create
    @salon = Salon.new(salon_params)

    if @salon.save
      redirect_to :action => 'list'
    else
      render :action => 'new'
    end
  end

  def edit
    @salon = Salon.find(params[:id])
  end



  def update
    @salon = Salon.find(params[:id])

    if @salon.update(salon_param)
      redirect_to :action => 'show', :id=>@salon
    else
      #@subjects = Subject.all
      #render :action => 'edit'
    end
  end

  def salon_param
    params.require(:salon).permit(:nombre, :horario, :localizacion)
  end


  def delete
    Salon.find(params[:id]).destroy
    redirect_to :action => 'list', notice: 'La peluqueria se ha borrado correctamente'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointment_helper.rb
module AppointmentHelper
end

app/helpers/citas_helper.rb
module CitasHelper
end

app/helpers/developers_helper.rb
module DevelopersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/peluqueria_helper.rb
module PeluqueriaHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/salon_helper.rb
module SalonHelper
end

app/views/appoinment/list.html.erb
<h1>Lista de citas</h1>
<ul><% @appointments.each do |appointment| %>
    <li>
      <%= link_to appointment.persona, appointment_path(appointment) %>
  <% end %></li>
</ul>

<div><%= link_to 'Crear cita', new_appointment_path %></div>

app/views/layouts/_footer.html.erb
<div class="row bg-light">
  <div class="col text-center">

  </div>
</div>

<div class="row bg-light">
  <div class="col text-center">
    <p>Grupo DS6 Prácticas| Pablo Rodriguez Avila | Miguel Medina Martinez</p>
    <p>Hair Assistance &copy; 2021</p>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light ">
  <div class="container-fluid">
    <a class="navbar-brand" href="#"><h1>Hair Assistance</h1></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/DS9/home/index"><h3>Inicio</h3></a>
        </li>

        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link active dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <h3>Peluquerias</h3>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="/DS9/salon/list">Mostrar peluquerias</a></li>
              <li><a class="dropdown-item" href="/DS9/salon/new">Añadir una peluqueria</a></li>
            </ul>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link active dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <h3>Citas</h3>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="/DS9/appointment/list">Mostrar citas</a></li>
              <li><a class="dropdown-item" href="/DS9/appointment/new">Añadir una cita</a></li>
            </ul>
          </li>
          
          <h3>
            <li class="nav-item">
              <%= link_to "Editar perfil",
                edit_user_registration_path,
                class: "nav-link active" %>
            </li>
          </h3>
          <h3>
          <li class="nav-item">
            <%= link_to "Cerrar sesion",
            destroy_user_session_path,
            method: :delete,
            class: "nav-link active" %>
          </li>
          </h3>
          <% else %>
            <h3>
              <li class="nav-item">
                <%= link_to "Registrarse",
                            new_user_registration_path,
                            class: "nav-link active" %>
              </li>
            </h3>


            <h3>
              <li class="nav-item">
                <%= link_to "Identificarse",
                            new_user_session_path,
                            class: "nav-link active" %>
              </li>
            </h3>
          <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hair Assistance</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>



  <body>
    <header>
      <%= render "layouts/header" %>
    </header>

    <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
  
    <%= yield %>

    <footer>
      <%= render "layouts/footer" %>
    </footer>

  </body>
  

</html>

app/views/layouts/footer.html.erb
Este es el footer

app/views/layouts/header.html.erb
THis is the header